### ISSUE TITLE
Decouple reference

### ISSUE THREAD

**Issue by plouj** [dvgica/healthful#1]
Are there any references to literature or case studies explaining why/how/when would decoupling healthchecks from the service makes sense?
https://github.com/dvgica/healthful/blob/1ac9584f3178489ee4f86472b81390d8c5e25480/README.md?plain=1#L15
At first glance it seems counterintuitive so more information would help new potential users make an informed decision.

**Comment by dvgica** [comment]
Hmm I don't have any references off-hand. Note that I'm not suggesting decoupling health checks from a _service_, rather decoupling them from any _servers_ the service contains.

> At first glance it seems counterintuitive

Can you elaborate on why? 

Maybe you're suggesting that a health check is more accurate if it's served by the same HTTP server that the service uses for other things? If so, there are a number of reasons why that isn't necessarily true or a good idea:

- What if the service has multiple HTTP servers, or one HTTP server and one Thrift server? The overall service health is then some combination of the health of all those different servers. I've found this situation to be quite frequent. Coupling the health check to just one of the service's servers doesn't make sense in this case.
- What if the service doesn't have an HTTP server at all? This is also pretty frequent (e.g. some kind of queue consumer)

Additionally, I think that serving a health check via the same server as your regular service endpoints could be downright problematic. What if the server exposes its endpoints publicly? You typically wouldn't want to expose health check endpoints to the world.

**Comment by dvgica** [comment]
I've updated the README with some of this reasoning, hope that helps.
